from handler import Handler
from validate import Validate
from mainpage import MainPage
from welcomepage import WelcomePage
from signup import SignUpPage
from signin import SignIn
from signout import SignOut
from newpost import NewPost
from editpost import EditPost
from deletepost import DeletePost
from singlepost import SinglePost
from likepost import LikePost
from dislikepost import DislikePost
from editcomment import EditComment
from deletecomment import DeleteComment
